[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''

	call defx#custom#column('icon', {
		\ 'directory_icon': '▸',
		\ 'opened_icon': '▾',
		\ 'root_icon': ' ',
		\ })

	call defx#custom#option('_', {
  \ 'winwidth': 40,
  \ 'split': 'vertical',
  \ 'direction': 'botright',
  \ 'show_ignored_files': 1,
  \ 'buffer_name': 'exproler',
  \ 'toggle': 1,
  \ 'resume': 1,
  \ 'columns': 'indent:icons:filename:mark',
  \ })

	" 'columns': 'indent:icons:filename:mark',

	autocmd WinNew * call defx#redraw()

	" open window
	nnoremap <silent>fs :<C-u>Defx -auto-cd -vertical-preview -floating-preview<CR>


	autocmd FileType defx call s:defx_my_settings()
	function! s:defx_my_settings() abort
		" Define mappings
		nnoremap <silent><buffer><expr> <CR>
			\ defx#is_directory() ?
			\ defx#do_action('open') :
			\ defx#do_action('multi', ['drop', 'quit'])


		" close window
		nnoremap <silent><buffer><expr> q
			\ defx#do_action('quit')

		" new file or directory(end with /)
		nnoremap <silent><buffer><expr> n
			\ defx#do_action('new_file')

		" remove
		nnoremap <silent><buffer><expr> d
			\ defx#do_action('remove')

		" h,l -> 上位、下位ディレクトリに移動
		" k,l -> ファイル移動
		nnoremap <silent><buffer><expr> h
			\ defx#do_action('cd', ['..'])
		nnoremap <silent><buffer><expr> j
			\ line('.') == line('$') ? 'gg' : 'j'
		nnoremap <silent><buffer><expr> k
			\ line('.') == 1 ? 'G' : 'k'
		nnoremap <silent><buffer><expr> l
			\ defx#do_action('open')

		" フォルダをトグルして開く
		nnoremap <silent><buffer><expr> o
			\ defx#do_action('open_tree', 'toggle')

		" フォルダをトグルして閉じる
		nnoremap <silent><buffer><expr> O
			\ defx#do_action('close_tree')

		" パスをyank
		nnoremap <silent><buffer><expr> yy
			\ defx#do_action('yank_path')

		" rename
		nnoremap <silent><buffer><expr> r
			\ defx#do_action('rename')

		" ファイルを開く
		nnoremap <silent><buffer><expr> i
			\ defx#do_action('drop', 'vsplit')

		" go to home directory
		nnoremap <silent><buffer><expr> ~
			\ defx#do_action('cd')

		" ファイルをプレビュー
		nnoremap <silent><buffer><expr> K
			\ defx#do_action('preview')

		" クリップボード/ディレクトリにファイルをコピー/ペースト/移動
		nnoremap <silent><buffer><expr> c
			\ defx#do_action('copy')
		nnoremap <silent><buffer><expr> p
			\ defx#do_action('paste')
		nnoremap <silent><buffer><expr> m
			\ defx#do_action('move')
    noremap <silent><buffer><expr> <Space>
			\ defx#do_action('toggle_select') . 'j'
    nnoremap <silent><buffer><expr> *
			\ defx#do_action('toggle_select_all')

	endfunction

'''

[[plugins]] repo = 'kristijanhusak/defx-icons'
hook_add = '''

'''
