[[plugins]]
repo = "nvim-telescope/telescope.nvim"
rev = "0.1.0"
depends = "plenary.nvim"
hook_add = '''

" Find files using Telescope command-line sugar.
nnoremap <Space>ff <cmd>Telescope find_files<CR>
nnoremap <Space>fg <cmd>Telescope live_grep<CR>
nnoremap <Space>fb <cmd>Telescope buffers<CR>
nnoremap <Space>fh <cmd>Telescope help_tags<CR>


lua << EOF
	require('telescope').setup{
		defaults = {
			-- Default configuration for telescope goes here:
			-- config_key = value,
			mappings = {
				i = {
				-- map actions.which_key to <C-h> (default: <C-/>)
				-- actions.which_key shows the mappings for your picker,
				-- e.g. git_{create, delete, ...}_branch for the git_branches picker
				["<C-h>"] = "which_key",
				},
			},
		},
		pickers = {
		-- Default configuration for builtin pickers goes here:
		-- picker_name = {
		--   picker_config_key = value,
		--   ...
		-- }
		-- Now the picker_config_key will be applied every time you call this
		-- builtin picker
		},
		extensions = {
		-- Your extension configuration goes here:
		-- extension_name = {
		--   extension_config_key = value,
		-- }
		-- please take a look at the readme of the extension you want to configure
		},
	}
EOF

'''
